CC=gcc 
CFLAGS=-O3
CLIBS=-lm

all: landscapeScaleModel.o mt19937ar.o
	$(CC) $(CFLAGS) landscapeScaleSimulation.o mt19937ar.o $(CLIBS) -o landscapeScaleSimulation 
	
clean:
	rm -f landscapeScaleSimulation *.o 
