CC=gcc 
CFLAGS=-g
CLIBS=-lm

all: landscapeScaleModel.o mt19937ar.o
	$(CC) $(CFLAGS) landscapeScaleModel.o mt19937ar.o $(CLIBS) -o landscapeScaleSimulation 
	
clean:
	rm -f landscapeScaleSimulation *.o 
